services:
  docs:
    image: financeapp_local_docs
    container_name: financeapp_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./financeapp:/app/financeapp:z
    ports:
      - '9000:9000'
    command: /start-docs
